#!/bin/sh
#
# Bootstrap FPC 2.0.0 from the checked-out source tree using tp2cc.
#
# Stages:
#   1. Copy a private clean source tree under build/.
#   2. Build `tp2cc`.
#   3. Translate `compiler/pp.pas` and its recursive `uses` tree to C++.
#   4. Compile and link the translated stage1 compiler.
#   5. Use stage1 `pp` to rebuild `compiler/pp.pas` as stage2.
#   6. Use stage2 `pp` to rebuild `compiler/pp.pas` again as stage3.
#
# This mirrors `bootstrap-fpc-1.sh` now that the FPC 2.0.0 emit pass is
# complete enough to justify a real stage1 compile instead of scout-only logs.

set -eu

cd "$(dirname "$0")"
ROOT=$(pwd)

JOBS="${JOBS:-8}"
CXX="${CXX:-g++}"
SOURCE_DIR="${FPC200_SRC:-$ROOT/../fpc-2.0.0/src}"

# Keep the translated compiler under the same instrumentation as the older
# bootstrap scripts so runtime failures show up as concrete UB/safety reports.
SAN="${SAN:--fsanitize=address,undefined -fno-omit-frame-pointer}"
CXXFLAGS="-std=gnu++20 -I. -O0 -g -pipe -fms-extensions -fpermissive -Wno-narrowing -Wno-microsoft-anon-tag -Wno-permissive $SAN"
export CXXFLAGS

# FPC frees most global state only at process exit. LSan then turns a normal
# compile into a nonzero exit status, which confuses the stage2/stage3 driver.
export ASAN_OPTIONS="${ASAN_OPTIONS:-detect_leaks=0}"

BOOT_ROOT="${BOOTSTRAP_ROOT:-$ROOT/build/fpc-2.0.0-bootstrap}"
CLEAN_SRC="$BOOT_ROOT/source"
STAGE1_DIR="$BOOT_ROOT/stage1"
STAGE2_DIR="$BOOT_ROOT/stage2"
STAGE3_DIR="$BOOT_ROOT/stage3"
STAGE1_LOGDIR="$BOOT_ROOT/compile-logs-stage1"
ENTRY_FILE="$SOURCE_DIR/compiler/pp.pas"
MSG_FILE="$SOURCE_DIR/compiler/msg/errore.msg"
STARTUP_AS="$CLEAN_SRC/rtl/linux/i386/prt0.as"

compiler_dir_flags() {
  printf '%s ' "-Fu$CLEAN_SRC/compiler" "-Fi$CLEAN_SRC/compiler"
  printf '%s ' "-Fu$CLEAN_SRC/compiler/i386" "-Fi$CLEAN_SRC/compiler/i386"
  # FPC 2.0.2 moved the shared x86 units (cpubase, result-flag enums,
  # common register metadata) under compiler/x86. Keep the older i386
  # path too: 2.0.0 still needs it and 2.0.2 needs both.
  if [ -d "$CLEAN_SRC/compiler/x86" ]; then
    printf '%s ' "-Fu$CLEAN_SRC/compiler/x86" "-Fi$CLEAN_SRC/compiler/x86"
  fi
  printf '%s ' "-Fu$CLEAN_SRC/compiler/systems" "-Fi$CLEAN_SRC/compiler/systems"
}

require_i386_toolchain() {
  machine="$($CXX -dumpmachine 2>/dev/null || true)"
  case "$machine" in
    i?86-*|i86pc-*)
      ;;
    *)
      echo "error: CXX='$CXX' targets '$machine', expected an i386/i686 toolchain" >&2
      echo "hint: guix shell --system=i686-linux binutils gcc-toolchain -- ./bootstrap-fpc-2.sh" >&2
      exit 1
      ;;
  esac
}

build_translator() {
  echo "== [1/7] build tp2cc translator =="
  # `build/obj/*.o` may have been produced by a previous host-arch build.
  # Rebuild from clean state so the i686 bootstrap shell never links a
  # mixed-architecture `tp2cc`.
  make clean
  make -j"$JOBS" build/bin/tp2cc
}

copy_clean_source() {
  echo "== [2/7] copy clean FPC 2.0.0 source tree =="
  rm -rf "$CLEAN_SRC"
  mkdir -p "$BOOT_ROOT"
  cp -a "$SOURCE_DIR" "$CLEAN_SRC"
  find "$CLEAN_SRC" \( -name "*.ppu" -o -name "*.o" -o -name "*.s" -o -name "*.a" \) \
    -type f -delete
}

write_bootstrap_cfg() {
  cat > "$STAGE1_DIR/ppc386.cfg" <<EOF
; generated by bootstrap-fpc-2.sh for translated FPC 2.0.0
-dI386
-Sg
-Fi$CLEAN_SRC/rtl/inc
-Fi$CLEAN_SRC/rtl/i386
-Fi$CLEAN_SRC/rtl/linux
-Fu$CLEAN_SRC/rtl/inc
-Fu$CLEAN_SRC/rtl/linux
-Fu$CLEAN_SRC/rtl/i386
-Fu$CLEAN_SRC/rtl/objpas
EOF
}

install_support_files() {
  stage_dir="$1"
  cp "$MSG_FILE" "$stage_dir/errore.msg"
  if [ "$stage_dir" != "$STAGE1_DIR" ]; then
    cp "$STAGE1_DIR/ppc386.cfg" "$stage_dir/ppc386.cfg"
  fi
}

build_stage1() {
  echo "== [3/7] translate FPC 2.0.0 compiler to C++ =="
  rm -rf "$STAGE1_DIR" "$STAGE1_LOGDIR"
  mkdir -p "$STAGE1_DIR"
  ./build/bin/tp2cc emit-all \
    -dFPC -dCPUI386 -dI386 -dLINUX -dUNIX \
    -dNOTARGETAMIGA -dNOTARGETBEOS -dNOTARGETFREEBSD \
    -dNOTARGETGO32V1 -dNOTARGETGO32V2 -dNOTARGETOS2 \
    -dNOTARGETPALMOS -dNOTARGETQNX -dNOTARGETSUNOS \
    -dNOTARGETWIN32 -dNOTARGETNETBSD -dNOTARGETOPENBSD \
    -dNOTARGETDARWIN -dNOTARGETNETWARE -dNOTARGETEMX \
    $(compiler_dir_flags) \
    -Fi"$CLEAN_SRC/rtl/inc" \
    -Fi"$CLEAN_SRC/rtl/i386" \
    -Fi"$CLEAN_SRC/rtl/linux" \
    "$CLEAN_SRC/compiler/pp.pas" "$STAGE1_DIR"
  write_bootstrap_cfg
  install_support_files "$STAGE1_DIR"

  echo "== [4/7] compile and link translated stage1 compiler =="
  JOBS="$JOBS" CXX="$CXX" LOGDIR="$STAGE1_LOGDIR" \
    tools/compile_emitted.sh "$STAGE1_DIR"
  if grep -q '^FAIL ' "$STAGE1_LOGDIR/build.txt"; then
    cat "$STAGE1_LOGDIR/summary.txt" >&2
    exit 1
  fi
  (
    cd "$STAGE1_DIR"
    "$CXX" -O0 -g3 $SAN p_*.o -o pp
  )
}

compile_pp_stage() {
  stage_name="$1"
  pp_bin="$2"
  cfg_dir="$3"
  out_dir="$4"

  echo "== [$stage_name] compile compiler/pp.pas =="
  rm -rf "$out_dir"
  mkdir -p "$out_dir"
  PP="$pp_bin" \
  PPC_CONFIG_PATH="$cfg_dir" \
  FPCDIR="$CLEAN_SRC" \
  STARTUP_AS="$STARTUP_AS" \
    "$ROOT/use-fpc.sh" \
      $(compiler_dir_flags) \
      "-o$out_dir/pp" \
      "$CLEAN_SRC/compiler/pp.pas"
  install_support_files "$out_dir"
}

verify_compiler() {
  pp_bin="$1"
  cfg_dir="$2"
  help_out=$(mktemp "${TMPDIR:-/tmp}/tp2cc-bootstrap-help.XXXXXX")
  if PPC_CONFIG_PATH="$cfg_dir" FPCDIR="$CLEAN_SRC" "$pp_bin" -h >"$help_out" 2>&1; then
    :
  fi
  if ! grep -q "Free Pascal Compiler version" "$help_out"; then
    cat "$help_out" >&2
    rm -f "$help_out"
    exit 1
  fi
  rm -f "$help_out"
}

if [ ! -d "$SOURCE_DIR" ]; then
  echo "error: FPC200 source tree not found: $SOURCE_DIR" >&2
  exit 1
fi

if [ ! -f "$ENTRY_FILE" ]; then
  echo "error: compiler entry file not found: $ENTRY_FILE" >&2
  exit 1
fi

if [ ! -f "$MSG_FILE" ]; then
  echo "error: message file not found: $MSG_FILE" >&2
  exit 1
fi

require_i386_toolchain
build_translator
copy_clean_source
build_stage1

compile_pp_stage "5/7" "$STAGE1_DIR/pp" "$STAGE1_DIR" "$STAGE2_DIR"
verify_compiler "$STAGE2_DIR/pp" "$STAGE2_DIR"

compile_pp_stage "6/7" "$STAGE2_DIR/pp" "$STAGE2_DIR" "$STAGE3_DIR"
verify_compiler "$STAGE3_DIR/pp" "$STAGE3_DIR"

echo "== [7/7] bootstrap summary =="
echo "stage1: $STAGE1_DIR/pp"
echo "stage2: $STAGE2_DIR/pp"
echo "stage3: $STAGE3_DIR/pp"
