#!/bin/sh
#
# Bootstrap-test the actual armhf/linux FPC 2.2.4 variant that Guix builds.
#
# Guix builds FPC 2.2.4 armhf through the package bootstrap path:
#   1. copy a private clean source tree
#   2. build `tp2cc`
#   3. emit a translated stage1 compiler with armhf/linux predefines
#   4. compile and link that translated stage1 `pp`
#   5. build `utils/data2inc` with stage1
#   6. run `make compiler_cycle` with stage1
#

set -eu

cd "$(dirname "$0")"
ROOT=$(pwd)

JOBS="${JOBS:-8}"
CXX="${CXX:-g++}"
CC="${CC:-gcc}"
SOURCE_DIR="${FPC2_SRC:-$ROOT/../fpc-2.2.4}"

fpc_source_version() {
  v="$SOURCE_DIR/compiler/version.pas"
  [ -r "$v" ] || { echo "unknown"; return; }
  awk -F"'" '
    /version_nr *=/ { vn=$2 }
    /release_nr *=/ { rn=$2 }
    /patch_nr *=/   { pn=$2 }
    END { if (vn != "") print vn "." rn "." pn; else print "unknown" }
  ' "$v"
}

echo "FPC source: $SOURCE_DIR (version $(fpc_source_version))"

SAN="${SAN:--fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=address,undefined}"
CXXFLAGS="-std=gnu++20 -I. -O0 -g -pipe -Wno-narrowing -Wno-invalid-offsetof $SAN"
CFLAGS="-std=gnu11 -O0 -g -pipe $SAN"
export CXXFLAGS
export CFLAGS

export ASAN_OPTIONS="${ASAN_OPTIONS:-detect_leaks=0:halt_on_error=1:abort_on_error=1:print_stacktrace=1}"
export UBSAN_OPTIONS="${UBSAN_OPTIONS:-halt_on_error=1:print_stacktrace=1}"

BOOT_ROOT="${BOOTSTRAP_ROOT:-$ROOT/build/fpc-2-arm-bootstrap}"
HOST_BUILD="${TP2CC_BUILD:-$ROOT/build-tp2cc-host}"
CLEAN_SRC="$BOOT_ROOT/source"
STAGE1_DIR="$BOOT_ROOT/stage1"
STAGE1_LOGDIR="$BOOT_ROOT/compile-logs-stage1"
MSG_FILE="$SOURCE_DIR/compiler/msg/errore.msg"
RUNTIME_SHIM="$ROOT/include/tp2cc_rt/fenv_shim.c"
PPC_NAME="ppcarm"

require_arm_toolchain() {
  machine="$($CXX -dumpmachine 2>/dev/null || true)"
  case "$machine" in
    arm*linux*|armv*linux*)
      ;;
    *)
      echo "error: CXX='$CXX' targets '$machine', expected a native arm-linux toolchain" >&2
      echo "hint: run this on the actual armhf-linux environment you want to test" >&2
      exit 1
      ;;
  esac
}

build_translator() {
  echo "== [1/6] build tp2cc translator =="
  rm -rf "$HOST_BUILD"
  make -j"$JOBS" BUILD="$HOST_BUILD" "$HOST_BUILD/bin/tp2cc"
}

copy_clean_source() {
  echo "== [2/6] copy clean FPC 2.2.4 source tree =="
  rm -rf "$CLEAN_SRC"
  mkdir -p "$BOOT_ROOT"
  cp -a "$SOURCE_DIR" "$CLEAN_SRC"
  find "$CLEAN_SRC" \( -name "*.ppu" -o -name "*.o" -o -name "*.s" -o -name "*.a" \) \
    -type f -delete
}

compiler_dir_flags() {
  printf '%s ' "-Fu$CLEAN_SRC/compiler" "-Fi$CLEAN_SRC/compiler"
  printf '%s ' "-Fu$CLEAN_SRC/compiler/arm" "-Fi$CLEAN_SRC/compiler/arm"
  printf '%s ' "-Fu$CLEAN_SRC/compiler/systems" "-Fi$CLEAN_SRC/compiler/systems"
}

write_bootstrap_cfg() {
  # FPC 2.2.4's options parser looks for `fpc.cfg` under PPC_CONFIG_PATH.
  cat > "$STAGE1_DIR/fpc.cfg" <<EOF
; generated by bootstrap-fpc-2-arm.sh for translated FPC 2.2.4 armhf/linux
-dARM
-dEXTERN_MSG
-Sg
-Fi$CLEAN_SRC/rtl/inc
-Fi$CLEAN_SRC/rtl/arm
-Fi$CLEAN_SRC/rtl/linux
-Fi$CLEAN_SRC/rtl/linux/arm
-Fi$CLEAN_SRC/rtl/unix
-Fi$CLEAN_SRC/rtl/objpas
-Fi$CLEAN_SRC/rtl/objpas/sysutils
-Fu$CLEAN_SRC/rtl/inc
-Fu$CLEAN_SRC/rtl/linux
-Fu$CLEAN_SRC/rtl/arm
-Fu$CLEAN_SRC/rtl/linux/arm
-Fu$CLEAN_SRC/rtl/unix
-Fu$CLEAN_SRC/rtl/objpas
EOF
}

install_support_files() {
  cp "$MSG_FILE" "$STAGE1_DIR/errore.msg"
}

build_stage1() {
  echo "== [3/6] translate FPC 2.2.4 armhf compiler to C++ =="
  rm -rf "$STAGE1_DIR" "$STAGE1_LOGDIR"
  mkdir -p "$STAGE1_DIR"

  # Use the same target-prune and feature defines as the Guix armhf package
  # bootstrap. These macros choose which target-specific compiler units are
  # visible to tp2cc during translation.
  common_defines="\
-dFPC -dEXTERN_MSG \
-dVER2 -dVER2_2 -dVER2_2_4 \
-dLINUX -dUNIX -dHASUNIX \
-dPARAOUTFILE -dRESSTRSECTIONS \
-dFPC_HASFIXED64BITVARIANT \
-dFPC_HASINTERNALOLEVARIANT2VARIANTCAST \
-dFPC_HAS_VARSETS -dFPC_HAS_VALGRINDBOOL -dFPC_HAS_STR_CURRENCY \
-dFPC_REAL2REAL_FIXED \
-dFPC_STRTOCHARARRAYPROC -dFPC_STRTOSHORTSTRINGPROC \
-dFPC_OBJFPC_EXTENDED_IF \
-dFPC_SUPPORTS_UNALIGNED -dFPC_UNALIGNED_FIXED \
-dFPC_HAS_MEMBAR -dFPC_NEW_BIGENDIAN_SETS -dFPC_SETBASE_USED \
-dSTR_CONCAT_PROCS \
-dFPC_HAS_FEATURE_SUPPORT \
-dFPC_HAS_TYPE_DOUBLE -dFPC_HAS_TYPE_SINGLE \
-dFPC_LINK_STATIC \
-dFPC_HAS_FEATURE_HEAP -dFPC_HAS_FEATURE_INITFINAL \
-dFPC_HAS_FEATURE_RTTI -dFPC_HAS_FEATURE_CLASSES \
-dFPC_HAS_FEATURE_EXCEPTIONS -dFPC_HAS_FEATURE_EXITCODE \
-dFPC_HAS_FEATURE_ANSISTRINGS -dFPC_HAS_FEATURE_WIDESTRINGS \
-dFPC_HAS_FEATURE_TEXTIO -dFPC_HAS_FEATURE_CONSOLEIO \
-dFPC_HAS_FEATURE_FILEIO -dFPC_HAS_FEATURE_RANDOM \
-dFPC_HAS_FEATURE_VARIANTS -dFPC_HAS_FEATURE_OBJECTS \
-dFPC_HAS_FEATURE_DYNARRAYS -dFPC_HAS_FEATURE_THREADING \
-dFPC_HAS_FEATURE_COMMANDARGS -dFPC_HAS_FEATURE_PROCESSES \
-dFPC_HAS_FEATURE_STACKCHECK \
-dNoDbgDwarf \
-dNOTARGETAMIGA -dNOTARGETBEOS -dNOTARGETFREEBSD \
-dNOTARGETGO32V1 -dNOTARGETGO32V2 -dNOTARGETOS2 \
-dNOTARGETPALMOS -dNOTARGETQNX -dNOTARGETSUNOS \
-dNOTARGETWIN32 -dNOTARGETNETBSD -dNOTARGETOPENBSD \
-dNOTARGETDARWIN -dNOTARGETNETWARE -dNOTARGETEMX"

  armhf_defines="\
-dARM -dCPU32 -dCPUARM \
-dFPC_INCLUDE_SOFTWARE_INT64_TO_DOUBLE \
-dFPC_CURRENCY_IS_INT64 -dFPC_COMP_IS_INT64 \
-dCPUARMV3 -dFPUFPA \
-dENDIAN_LITTLE -dFPC_LITTLE_ENDIAN"

  "$HOST_BUILD/bin/tp2cc" emit-all \
    $common_defines \
    $armhf_defines \
    $(compiler_dir_flags) \
    -Fi"$CLEAN_SRC/rtl/inc" \
    -Fi"$CLEAN_SRC/rtl/arm" \
    -Fi"$CLEAN_SRC/rtl/linux" \
    "$CLEAN_SRC/compiler/pp.pas" "$STAGE1_DIR"
  write_bootstrap_cfg
  install_support_files

  echo "== [4/6] compile and link translated stage1 compiler =="
  JOBS="$JOBS" CXX="$CXX" LOGDIR="$STAGE1_LOGDIR" \
    tools/compile_emitted.sh "$STAGE1_DIR"
  if grep -q '^FAIL ' "$STAGE1_LOGDIR/build.txt"; then
    cat "$STAGE1_LOGDIR/summary.txt" >&2
    exit 1
  fi
  (
    cd "$STAGE1_DIR"
    "$CC" $CFLAGS -c "$RUNTIME_SHIM" -o tp2cc_fenv_shim.o
    "$CXX" -O0 -g3 $SAN p_*.o tp2cc_fenv_shim.o -lm -o pp
  )
}

run_compiler_cycle() {
  echo "== [5/6] build data2inc with stage1 =="
  (
    cd "$CLEAN_SRC"
    PPC_CONFIG_PATH="$STAGE1_DIR" \
    FPCDIR="$CLEAN_SRC" \
      "$STAGE1_DIR/pp" "-FEutils/" "utils/data2inc.pp"
  )

  echo "== [6/6] run compiler_cycle with stage1 =="
  (
    cd "$CLEAN_SRC"
    export PPC_CONFIG_PATH="$STAGE1_DIR"
    export FPCDIR="$CLEAN_SRC"
    export DATA2INC="$CLEAN_SRC/utils/data2inc"
    make -j"$JOBS" "FPC=$STAGE1_DIR/pp" compiler_cycle
  )
}

verify_outputs() {
  if [ ! -x "$CLEAN_SRC/compiler/$PPC_NAME" ]; then
    echo "error: compiler_cycle did not produce $CLEAN_SRC/compiler/$PPC_NAME" >&2
    exit 1
  fi
  help_out=$(mktemp "${TMPDIR:-/tmp}/tp2cc-bootstrap-arm-help.XXXXXX")
  PPC_CONFIG_PATH="$STAGE1_DIR" \
  FPCDIR="$CLEAN_SRC" \
    "$CLEAN_SRC/compiler/$PPC_NAME" -h >"$help_out" 2>&1 || true
  if ! grep -q "Free Pascal Compiler version" "$help_out"; then
    cat "$help_out" >&2
    rm -f "$help_out"
    exit 1
  fi
  rm -f "$help_out"
}

if [ ! -d "$SOURCE_DIR" ]; then
  echo "error: FPC 2.2.4 source tree not found: $SOURCE_DIR" >&2
  exit 1
fi

if [ ! -f "$MSG_FILE" ]; then
  echo "error: message file not found: $MSG_FILE" >&2
  exit 1
fi

require_arm_toolchain
copy_clean_source
build_translator
build_stage1
run_compiler_cycle
verify_outputs

echo "== bootstrap summary =="
echo "stage1 translated compiler: $STAGE1_DIR/pp"
echo "compiler_cycle result:      $CLEAN_SRC/compiler/$PPC_NAME"
