#!/bin/sh
#
# Bootstrap FPC 1.0.6 from the checked-out source tree using tp2cc.
#
# Stages:
#   1. Build `tp2cc`.
#   2. Translate `compiler/pp.pas` from FPC 1.0.6 to C++ and link stage1.
#   3. Use stage1 `pp` to rebuild `compiler/pp.pas` as stage2.
#   4. Use stage2 `pp` to rebuild `compiler/pp.pas` again as stage3.
#
# The 1.0.6 source tree can contain stale `.ppu`/`.o` artifacts from older
# compilers. Those confuse the translated compiler, so this script always
# works from a private cleaned copy under `build/`.

set -eu

cd "$(dirname "$0")"
ROOT=$(pwd)

JOBS="${JOBS:-8}"
CXX="${CXX:-g++}"
SOURCE_DIR="${FPC106_SRC:-$ROOT/../fpc-1.0.6/source}"

# ASan and UBSan catch packed-field misbindings, vptr downcasts on foreign
# object hierarchies, oob reads on wrongly-cast records, etc. -- exactly
# the latent UB tp2cc inherits from decades-old FPC sources. Keep these
# armed by default; `SAN=` disables for profiling or release runs. Make
# sanitizer findings fatal so a bootstrap never reports success while
# printing active UB.
SAN="${SAN:--fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=address,undefined}"
CXXFLAGS="-std=gnu++20 -I. -O0 -g -pipe -Wno-narrowing $SAN"
export CXXFLAGS

# FPC relies on process-lifetime cleanup: option parsing, symbol tables,
# asmlists, etc. are strung up through global pointers and freed only by
# exit. That leaks by design, and LSan turning each exit into a nonzero
# status breaks the stage2/stage3 use-fpc drivers (which read pp's exit
# code as "compile failed"). Leave heap/stack checking armed; just turn
# off the exit-time leak scan while keeping every other sanitizer hit
# fatal.
export ASAN_OPTIONS="${ASAN_OPTIONS:-detect_leaks=0:halt_on_error=1:abort_on_error=1:print_stacktrace=1}"
export UBSAN_OPTIONS="${UBSAN_OPTIONS:-halt_on_error=1:print_stacktrace=1}"
BOOT_ROOT="${BOOTSTRAP_ROOT:-$ROOT/build/fpc-1.0.6-bootstrap}"
HOST_BUILD="${TP2CC_BUILD:-$ROOT/build-tp2cc-host}"
CLEAN_SRC="$BOOT_ROOT/source"
STAGE1_DIR="$BOOT_ROOT/stage1"
STAGE2_DIR="$BOOT_ROOT/stage2"
STAGE3_DIR="$BOOT_ROOT/stage3"
STAGE1_LOGDIR="$BOOT_ROOT/compile-logs-stage1"
ENTRY_FILE="$SOURCE_DIR/compiler/pp.pas"
MSG_FILE="$SOURCE_DIR/compiler/msg/errore.msg"
STARTUP_AS="$CLEAN_SRC/rtl/linux/i386/prt0.as"

require_i386_toolchain() {
  machine="$($CXX -dumpmachine 2>/dev/null || true)"
  case "$machine" in
    i?86-*|i86pc-*)
      ;;
    *)
      echo "error: CXX='$CXX' targets '$machine', expected an i386/i686 toolchain" >&2
      echo "hint: guix shell -s i686-linux binutils gcc-toolchain -- ./bootstrap-fpc.sh" >&2
      exit 1
      ;;
  esac
}

build_translator() {
  echo "== [2/7] build tp2cc translator =="
  # Keep the host translator build separate from the bootstrap output tree.
  # That avoids mixed-architecture object reuse and does not require wiping
  # the default `build/` directory just to rebuild `tp2cc` for i686.
  rm -rf "$HOST_BUILD"
  make -j"$JOBS" BUILD="$HOST_BUILD" "$HOST_BUILD/bin/tp2cc"
}

copy_clean_source() {
  echo "== [1/7] copy clean FPC 1.0.6 source tree =="
  rm -rf "$CLEAN_SRC"
  mkdir -p "$BOOT_ROOT"
  cp -a "$SOURCE_DIR" "$CLEAN_SRC"
  find "$CLEAN_SRC" \( -name "*.ppu" -o -name "*.o" -o -name "*.s" -o -name "*.a" \) \
    -type f -delete
}

write_bootstrap_cfg() {
  cat > "$STAGE1_DIR/ppc386.cfg" <<EOF
; generated by bootstrap-fpc.sh for translated FPC 1.0.6
-dI386
-Sg
-Fi$CLEAN_SRC/rtl/inc
-Fi$CLEAN_SRC/rtl/i386
-Fi$CLEAN_SRC/rtl/linux
-Fi$CLEAN_SRC/rtl/unix
-Fi$CLEAN_SRC/rtl/objpas
-Fu$CLEAN_SRC/rtl/inc
-Fu$CLEAN_SRC/rtl/linux
-Fu$CLEAN_SRC/rtl/i386
-Fu$CLEAN_SRC/rtl/unix
-Fu$CLEAN_SRC/rtl/objpas
-Fi$CLEAN_SRC/fcl/inc
-Fi$CLEAN_SRC/fcl/linux
-Fu$CLEAN_SRC/fcl/inc
-Fu$CLEAN_SRC/fcl/linux
EOF
}

install_support_files() {
  stage_dir="$1"
  cp "$MSG_FILE" "$stage_dir/errore.msg"
  if [ "$stage_dir" != "$STAGE1_DIR" ]; then
    cp "$STAGE1_DIR/ppc386.cfg" "$stage_dir/ppc386.cfg"
  fi
}

build_stage1() {
  echo "== [3/7] translate FPC 1.0.6 compiler to C++ =="
  rm -rf "$STAGE1_DIR" "$STAGE1_LOGDIR"
  mkdir -p "$STAGE1_DIR"
  "$HOST_BUILD/bin/tp2cc" emit-all \
    -dFPC -dI386 -dCPU86 -dLINUX -dUNIX -dEXTERN_MSG \
    -dNOTARGETAMIGA -dNOTARGETBEOS -dNOTARGETFREEBSD \
    -dNOTARGETGO32V1 -dNOTARGETGO32V2 -dNOTARGETOS2 \
    -dNOTARGETPALMOS -dNOTARGETQNX -dNOTARGETSUNOS \
    -dNOTARGETWIN32 \
    -Fu"$CLEAN_SRC/compiler" \
    -Fu"$CLEAN_SRC/compiler/i386" \
    -Fu"$CLEAN_SRC/compiler/targets" \
    -Fi"$CLEAN_SRC/rtl/inc" \
    -Fi"$CLEAN_SRC/rtl/i386" \
    -Fi"$CLEAN_SRC/rtl/linux" \
    "$ENTRY_FILE" "$STAGE1_DIR"
  write_bootstrap_cfg
  install_support_files "$STAGE1_DIR"

  echo "== [4/7] compile and link translated stage1 compiler =="
  JOBS="$JOBS" CXX="$CXX" LOGDIR="$STAGE1_LOGDIR" \
    tools/compile_emitted.sh "$STAGE1_DIR"
  if grep -q '^FAIL ' "$STAGE1_LOGDIR/build.txt"; then
    cat "$STAGE1_LOGDIR/summary.txt" >&2
    exit 1
  fi
  (
    cd "$STAGE1_DIR"
    "$CXX" -O0 -g3 $SAN p_*.o -o pp
  )
}

compile_pp_stage() {
  stage_name="$1"
  pp_bin="$2"
  cfg_dir="$3"
  out_dir="$4"

  echo "== [$stage_name] compile compiler/pp.pas =="
  rm -rf "$out_dir"
  mkdir -p "$out_dir"
  PP="$pp_bin" \
  PPC_CONFIG_PATH="$cfg_dir" \
  FPCDIR="$CLEAN_SRC" \
  STARTUP_AS="$STARTUP_AS" \
    "$ROOT/use-fpc.sh" \
      "-Fi$CLEAN_SRC/compiler" \
      "-Fi$CLEAN_SRC/compiler/i386" \
      "-Fi$CLEAN_SRC/compiler/targets" \
      "-Fu$CLEAN_SRC/compiler" \
      "-Fu$CLEAN_SRC/compiler/i386" \
      "-Fu$CLEAN_SRC/compiler/targets" \
      "-o$out_dir/pp" \
      "$CLEAN_SRC/compiler/pp.pas"
  install_support_files "$out_dir"
}

verify_compiler() {
  pp_bin="$1"
  cfg_dir="$2"
  help_out=$(mktemp "${TMPDIR:-/tmp}/tp2cc-bootstrap-help.XXXXXX")
  if PPC_CONFIG_PATH="$cfg_dir" FPCDIR="$CLEAN_SRC" "$pp_bin" -h >"$help_out" 2>&1; then
    :
  fi
  if ! grep -q "Free Pascal Compiler version" "$help_out"; then
    cat "$help_out" >&2
    rm -f "$help_out"
    exit 1
  fi
  rm -f "$help_out"
}

if [ ! -d "$SOURCE_DIR" ]; then
  echo "error: FPC106 source tree not found: $SOURCE_DIR" >&2
  exit 1
fi

if [ ! -f "$ENTRY_FILE" ]; then
  echo "error: compiler entry file not found: $ENTRY_FILE" >&2
  exit 1
fi

if [ ! -f "$MSG_FILE" ]; then
  echo "error: message file not found: $MSG_FILE" >&2
  exit 1
fi

require_i386_toolchain
copy_clean_source
build_translator
build_stage1

compile_pp_stage "5/7" "$STAGE1_DIR/pp" "$STAGE1_DIR" "$STAGE2_DIR"
verify_compiler "$STAGE2_DIR/pp" "$STAGE2_DIR"

compile_pp_stage "6/7" "$STAGE2_DIR/pp" "$STAGE2_DIR" "$STAGE3_DIR"
verify_compiler "$STAGE3_DIR/pp" "$STAGE3_DIR"

echo "== [7/7] bootstrap summary =="
echo "stage1: $STAGE1_DIR/pp"
echo "stage2: $STAGE2_DIR/pp"
echo "stage3: $STAGE3_DIR/pp"
