#!/bin/sh
#
# Bootstrap FPC 2 from the checked-out source tree using tp2cc.
#
# Stages:
#   1. Copy a private clean source tree under build/.
#   2. Build `tp2cc`.
#   3. Translate `compiler/pp.pas` and its recursive `uses` tree to C++.
#   4. Compile and link the translated stage1 compiler.
#   5. Use stage1 `pp` to rebuild `compiler/pp.pas` as stage2.
#   6. Use stage2 `pp` to rebuild `compiler/pp.pas` again as stage3.
#

set -eu

cd "$(dirname "$0")"
ROOT=$(pwd)

JOBS="${JOBS:-8}"
CXX="${CXX:-g++}"
CC="${CC:-gcc}"
if [ -z "${FPC2_SRC:-}" ]; then
  echo "error: FPC2_SRC must be set to the FPC 2.x source tree to bootstrap" >&2
  exit 1
fi
SOURCE_DIR="$FPC2_SRC"

# Print the source path AND its declared version up front so a silent
# target mismatch can't hide.
fpc_source_version() {
  local v="$SOURCE_DIR/compiler/version.pas"
  [ -r "$v" ] || { echo "unknown"; return; }
  awk -F"'" '
    /version_nr *=/ { vn=$2 }
    /release_nr *=/ { rn=$2 }
    /patch_nr *=/   { pn=$2 }
    END { if (vn != "") print vn"."rn"."pn; else print "unknown" }
  ' "$v"
}
echo "FPC source: $SOURCE_DIR (version $(fpc_source_version))"

# Keep the translated compiler under sanitizer instrumentation, but make
# findings fatal so a "successful" bootstrap never masks active UB.
SAN="${SAN:--fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=address,undefined}"
CXXFLAGS="-std=gnu++20 -I. -O0 -g -pipe -fms-extensions -fpermissive -Wno-narrowing -Wno-microsoft-anon-tag -Wno-permissive $SAN"
CFLAGS="-std=gnu11 -O0 -g -pipe $SAN"
export CXXFLAGS
export CFLAGS

# FPC frees most global state only at process exit. Disable leak checking, but
# keep everything else fatal so the bootstrap stops at the first sanitizer hit.
export ASAN_OPTIONS="${ASAN_OPTIONS:-detect_leaks=0:halt_on_error=1:abort_on_error=1:print_stacktrace=1}"
export UBSAN_OPTIONS="${UBSAN_OPTIONS:-halt_on_error=1:print_stacktrace=1}"

BOOT_ROOT="${BOOTSTRAP_ROOT:-$ROOT/build/fpc-2-bootstrap}"
HOST_BUILD="${TP2CC_BUILD:-$ROOT/build-tp2cc-host}"
CLEAN_SRC="$BOOT_ROOT/source"
STAGE1_DIR="$BOOT_ROOT/stage1"
STAGE2_DIR="$BOOT_ROOT/stage2"
STAGE3_DIR="$BOOT_ROOT/stage3"
STAGE1_LOGDIR="$BOOT_ROOT/compile-logs-stage1"
ENTRY_FILE="$SOURCE_DIR/compiler/pp.pas"
MSG_FILE="$SOURCE_DIR/compiler/msg/errore.msg"
STARTUP_AS="$CLEAN_SRC/rtl/linux/i386/prt0.as"
RUNTIME_SHIM="$ROOT/tp2cc_rt/fenv_shim.c"

compiler_dir_flags() {
  printf '%s ' "-Fu$CLEAN_SRC/compiler" "-Fi$CLEAN_SRC/compiler"
  printf '%s ' "-Fu$CLEAN_SRC/compiler/i386" "-Fi$CLEAN_SRC/compiler/i386"
  # FPC 2.0.2 moved the shared x86 units (cpubase, result-flag enums,
  # common register metadata) under compiler/x86. Keep the older i386
  # path too: 2.0.0 still needs it and 2.0.2 needs both.
  if [ -d "$CLEAN_SRC/compiler/x86" ]; then
    printf '%s ' "-Fu$CLEAN_SRC/compiler/x86" "-Fi$CLEAN_SRC/compiler/x86"
  fi
  printf '%s ' "-Fu$CLEAN_SRC/compiler/systems" "-Fi$CLEAN_SRC/compiler/systems"
}

require_i386_toolchain() {
  machine="$($CXX -dumpmachine 2>/dev/null || true)"
  case "$machine" in
    i?86-*|i86pc-*)
      ;;
    *)
      echo "error: CXX='$CXX' targets '$machine', expected an i386/i686 toolchain" >&2
      echo "hint: guix shell --system=i686-linux binutils gcc-toolchain -- ./bootstrap-fpc-2.sh" >&2
      exit 1
      ;;
  esac
}

build_translator() {
  echo "== [1/7] build tp2cc translator =="
  # Keep the host translator build separate from the bootstrap output tree.
  # That avoids mixed-architecture object reuse and does not require wiping
  # the entire `build/` directory just to rebuild `tp2cc` for i686.
  rm -rf "$HOST_BUILD"
  make -j"$JOBS" BUILD="$HOST_BUILD" "$HOST_BUILD/bin/tp2cc"
}

copy_clean_source() {
  echo "== [2/7] copy clean FPC 2 source tree =="
  rm -rf "$CLEAN_SRC"
  mkdir -p "$BOOT_ROOT"
  cp -a "$SOURCE_DIR" "$CLEAN_SRC"
  find "$CLEAN_SRC" \( -name "*.ppu" -o -name "*.o" -o -name "*.s" -o -name "*.a" \) \
    -type f -delete
}

write_bootstrap_cfg() {
  cat > "$STAGE1_DIR/ppc386.cfg" <<EOF
; generated by bootstrap-fpc-2.sh for translated FPC 2
; Exclude dbgdwarf for the current i386-linux bootstrap. This target's default
; debug format is still stabs, so dbgdwarf is not needed to build the compiler,
; and the dbgdwarf unit still uses array of const, which tp2cc does not yet
; support. Keep the define active from the start because cputarg.pas
; conditionally uses dbgdwarf when NoDbgDwarf is absent.
-dI386
-dNoDbgDwarf
-dEXTERN_MSG
-Sg
-Fi$CLEAN_SRC/rtl/inc
-Fi$CLEAN_SRC/rtl/i386
-Fi$CLEAN_SRC/rtl/linux
-Fi$CLEAN_SRC/rtl/linux/i386
-Fi$CLEAN_SRC/rtl/unix
-Fi$CLEAN_SRC/rtl/objpas
-Fi$CLEAN_SRC/rtl/objpas/sysutils
-Fu$CLEAN_SRC/rtl/inc
-Fu$CLEAN_SRC/rtl/linux
-Fu$CLEAN_SRC/rtl/i386
-Fu$CLEAN_SRC/rtl/linux/i386
-Fu$CLEAN_SRC/rtl/unix
-Fu$CLEAN_SRC/rtl/objpas
EOF
}

install_support_files() {
  stage_dir="$1"
  cp "$MSG_FILE" "$stage_dir/errore.msg"
  if [ "$stage_dir" != "$STAGE1_DIR" ]; then
    cp "$STAGE1_DIR/ppc386.cfg" "$stage_dir/ppc386.cfg"
  fi
}

build_stage1() {
  echo "== [3/7] translate FPC 2 compiler to C++ =="
  rm -rf "$STAGE1_DIR" "$STAGE1_LOGDIR"
  mkdir -p "$STAGE1_DIR"
  # Exclude dbgdwarf here for the same reason as in the generated cfg: the
  # current 2.2.4 i386 bootstrap does not need the dwarf debug-info backend,
  # and that unit still depends on unsupported array-of-const parsing. The
  # initial recursive unit walk must see the same target-unit graph as the
  # later stage compilers, or dbgdwarf gets pulled in before the cfg can
  # exclude it.
  # FPC's own `options.pas` defines `FPC_HAS_TYPE_EXTENDED` (and the
  # other `FPC_HAS_TYPE_*` macros) at runtime when targeting i386, but
  # that code never executes during tp2cc translation. The compiler
  # source uses `{$if defined(cpuextended) and defined(FPC_HAS_TYPE_EXTENDED)}`
  # to gate i386 80-bit-real codegen and the matching assembler-writer
  # cases; without these defines, tp2cc prunes the asm-writer cases
  # while leaving the codegen sites intact, producing `ait_real_80bit`
  # nodes the assembler can't write (internalerror 2006012201).
  "$HOST_BUILD/bin/tp2cc" emit-all \
    -dFPC -dCPUI386 -dI386 -dLINUX -dUNIX \
    -dFPC_HAS_TYPE_EXTENDED -dFPC_HAS_TYPE_DOUBLE \
    -dFPC_HAS_TYPE_SINGLE -dFPC_HAS_RESOURCES \
    -dNoDbgDwarf \
    -dNOTARGETAMIGA -dNOTARGETBEOS -dNOTARGETFREEBSD \
    -dNOTARGETGO32V1 -dNOTARGETGO32V2 -dNOTARGETOS2 \
    -dNOTARGETPALMOS -dNOTARGETQNX -dNOTARGETSUNOS \
    -dNOTARGETWIN32 -dNOTARGETNETBSD -dNOTARGETOPENBSD \
    -dNOTARGETDARWIN -dNOTARGETNETWARE -dNOTARGETEMX \
    $(compiler_dir_flags) \
    -Fi"$CLEAN_SRC/rtl/inc" \
    -Fi"$CLEAN_SRC/rtl/i386" \
    -Fi"$CLEAN_SRC/rtl/linux" \
    "$CLEAN_SRC/compiler/pp.pas" "$STAGE1_DIR"
  write_bootstrap_cfg
  install_support_files "$STAGE1_DIR"

  echo "== [4/7] compile and link translated stage1 compiler =="
  JOBS="$JOBS" CXX="$CXX" LOGDIR="$STAGE1_LOGDIR" \
    tools/compile_emitted.sh "$STAGE1_DIR"
  if grep -q '^FAIL ' "$STAGE1_LOGDIR/build.txt"; then
    cat "$STAGE1_LOGDIR/summary.txt" >&2
    exit 1
  fi
  (
    cd "$STAGE1_DIR"
    "$CC" $CFLAGS -c "$RUNTIME_SHIM" -o tp2cc_fenv_shim.o
    "$CXX" -O0 -g3 $SAN p_*.o tp2cc_fenv_shim.o -lm -o pp
  )
}

compile_pp_stage() {
  stage_name="$1"
  pp_bin="$2"
  cfg_dir="$3"
  out_dir="$4"

  echo "== [$stage_name] compile compiler/pp.pas =="
  rm -rf "$out_dir"
  mkdir -p "$out_dir"
  PP="$pp_bin" \
  PPC_CONFIG_PATH="$cfg_dir" \
  FPCDIR="$CLEAN_SRC" \
  STARTUP_AS="$STARTUP_AS" \
    "$ROOT/use-fpc.sh" \
      $(compiler_dir_flags) \
      "-o$out_dir/pp" \
      "$CLEAN_SRC/compiler/pp.pas"
  install_support_files "$out_dir"
}

verify_compiler() {
  pp_bin="$1"
  cfg_dir="$2"
  help_out=$(mktemp "${TMPDIR:-/tmp}/tp2cc-bootstrap-help.XXXXXX")
  if PPC_CONFIG_PATH="$cfg_dir" FPCDIR="$CLEAN_SRC" "$pp_bin" -h >"$help_out" 2>&1; then
    :
  fi
  if ! grep -q "Free Pascal Compiler version" "$help_out"; then
    cat "$help_out" >&2
    rm -f "$help_out"
    exit 1
  fi
  rm -f "$help_out"
}

if [ ! -d "$SOURCE_DIR" ]; then
  echo "error: FPC200 source tree not found: $SOURCE_DIR" >&2
  exit 1
fi

if [ ! -f "$ENTRY_FILE" ]; then
  echo "error: compiler entry file not found: $ENTRY_FILE" >&2
  exit 1
fi

if [ ! -f "$MSG_FILE" ]; then
  echo "error: message file not found: $MSG_FILE" >&2
  exit 1
fi

if [ ! -f "$RUNTIME_SHIM" ]; then
  echo "error: runtime shim not found: $RUNTIME_SHIM" >&2
  exit 1
fi

require_i386_toolchain
build_translator
copy_clean_source
build_stage1

compile_pp_stage "5/7" "$STAGE1_DIR/pp" "$STAGE1_DIR" "$STAGE2_DIR"
verify_compiler "$STAGE2_DIR/pp" "$STAGE2_DIR"

compile_pp_stage "6/7" "$STAGE2_DIR/pp" "$STAGE2_DIR" "$STAGE3_DIR"
verify_compiler "$STAGE3_DIR/pp" "$STAGE3_DIR"

echo "== [7/7] bootstrap summary =="
echo "stage1: $STAGE1_DIR/pp"
echo "stage2: $STAGE2_DIR/pp"
echo "stage3: $STAGE3_DIR/pp"
