#!/bin/sh
# End-to-end build: p2cc translator -> emit Pascal->C++ -> compile -> link pp.
#
# Steps:
#   1. make        -- build ./build/bin/p2cc (64-bit, host toolchain)
#   2. emit-all    -- translate pp.pas and its recursive `uses` tree to
#                     build/emitted/*.cc
#   3. compile     -- compile every emitted p_*.cc with 32-bit g++ from guix
#                     (fpc 0.99 targets i386; runtime assumes 32-bit pointers)
#   4. link        -- link build/emitted/pp from the reachable object files
#
# Run this inside an i386/i686 toolchain environment. For example:
#   guix shell --system=i686-linux gcc-toolchain binutils -- ./build-fpc.sh
#
# Do NOT run with a host 64-bit g++ -- the runtime
# (p2cc_rt/prelude.h) is sized for 32-bit pointers and the build may
# succeed while the translated compiler misbehaves badly at runtime.

set -eu

cd "$(dirname "$0")"
ROOT="$(pwd)"

JOBS="${JOBS:-8}"
CXX="${CXX:-g++}"
ENTRY_FILE="../rpm/compiler/pp.pas"
OUT_DIR="build/emitted"
RPM_DIR="$ROOT/../rpm"

MACHINE="$($CXX -dumpmachine 2>/dev/null || true)"
case "$MACHINE" in
  i?86-*|i86pc-*)
    ;;
  *)
    echo "error: CXX='$CXX' targets '$MACHINE', expected an i386/i686 toolchain" >&2
    echo "hint: guix shell --system=i686-linux gcc-toolchain binutils -- ./build-fpc.sh" >&2
    exit 1
    ;;
esac

echo "== [1/4] build p2cc translator =="
make clean
make -j"$JOBS"

echo "== [2/4] emit C++ from Pascal =="
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
./build/bin/p2cc emit-all "$ENTRY_FILE" "$OUT_DIR"
cp "$RPM_DIR/compiler/errore.msg" "$OUT_DIR/errore.msg"
cat > "$OUT_DIR/ppc386.cfg" <<EOF
; generated by build-fpc.sh for the translated bootstrap compiler
-dI386
-Sg
-Fi$RPM_DIR/rtl/inc
-Fi$RPM_DIR/rtl/i386
-Fi$RPM_DIR/rtl/linux
-Fu$RPM_DIR/rtl/inc
-Fu$RPM_DIR/rtl/linux
-Fu$RPM_DIR/rtl/i386
-Fu$RPM_DIR/rtl/objpas
-Fu$RPM_DIR/rtl/fakertl
EOF

echo "== [3/4] compile emitted units (32-bit) =="
JOBS="$JOBS" CXX="$CXX" tools/compile_emitted.sh "$OUT_DIR"

echo "== [4/4] link pp =="
cd "$OUT_DIR"
$CXX -O0 -g p_*.o -o pp

ls -la pp
echo "ok: $ROOT/$OUT_DIR/pp"
