#include "emit_makefile.h"

#include <algorithm>
#include <sstream>
#include <string_view>

namespace tp2cc {
namespace {

void sort_unique(std::vector<std::string>* items) {
  std::sort(items->begin(), items->end());
  items->erase(std::unique(items->begin(), items->end()), items->end());
}

void write_list(std::ostringstream& out, std::string_view name,
                const std::vector<std::string>& items) {
  out << name << " :=";
  if (items.empty()) {
    out << '\n';
    return;
  }
  out << " \\\n";
  for (size_t i = 0; i < items.size(); ++i) {
    out << "  " << items[i];
    if (i + 1 != items.size()) out << " \\";
    out << '\n';
  }
}

}  // namespace

std::string emit_makefile(const EmittedBuildManifest& manifest) {
  std::vector<std::string> cc_sources = manifest.cc_sources;
  std::vector<std::string> headers = manifest.headers;
  sort_unique(&cc_sources);
  sort_unique(&headers);

  std::ostringstream out;
  out << "# generated by tp2cc\n";
  out << "# TP2CC_ROOT must contain tp2cc_rt/prelude.h.\n";
  out << "CXX = g++\n";
  out << "CC = gcc\n";
  out << "TP2CC_ROOT = "
      << (manifest.tp2cc_root.empty() ? "." : manifest.tp2cc_root) << '\n';
  out << "CPPFLAGS = -I. -I$(TP2CC_ROOT)\n";
  out << "CXXFLAGS = -std=gnu++20 -O0 -pipe "
         "-Wno-narrowing\n";
  out << "CFLAGS = -std=gnu11 -O0 -pipe\n";
  out << "EXTRA_OBJS =\n";
  out << "LDFLAGS =\n";
  out << "LDLIBS = -lm\n\n";

  write_list(out, "CC_SRCS", cc_sources);
  write_list(out, "HDRS", headers);
  out << "CC_OBJS := $(CC_SRCS:.cc=.o)\n";
  if (!manifest.program_name.empty()) {
    out << "PROGRAM = " << manifest.program_name << '\n';
  }
  out << '\n';

  out << ".PHONY: all objects clean\n";
  if (!manifest.program_name.empty()) {
    out << "all: $(PROGRAM)\n";
  } else {
    out << "all: objects\n";
  }
  out << "objects: $(CC_OBJS)\n\n";

  out << "p_%.o: p_%.cc $(HDRS)\n";
  out << "\t$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@\n\n";

  if (!manifest.program_name.empty()) {
    out << "$(PROGRAM): $(CC_OBJS) $(EXTRA_OBJS)\n";
    out << "\t$(CXX) $(CXXFLAGS) $(LDFLAGS) $^ $(LDLIBS) -o $@\n\n";
  }

  out << "clean:\n";
  out << "\trm -f $(CC_OBJS)";
  if (!manifest.program_name.empty()) out << " $(PROGRAM)";
  out << '\n';
  return out.str();
}

}  // namespace tp2cc
