#include "emit_makefile.h"

#include <algorithm>
#include <sstream>
#include <string_view>

namespace tp2cc {
namespace {

void sort_unique(std::vector<std::string>* items) {
  std::sort(items->begin(), items->end());
  items->erase(std::unique(items->begin(), items->end()), items->end());
}

void write_list(std::ostringstream& out, std::string_view name,
                const std::vector<std::string>& items) {
  out << name << " :=";
  if (items.empty()) {
    out << '\n';
    return;
  }
  out << " \\\n";
  for (size_t i = 0; i < items.size(); ++i) {
    out << "  " << items[i];
    if (i + 1 != items.size()) out << " \\";
    out << '\n';
  }
}

std::string shell_quote(std::string_view s) {
  std::string out;
  out.reserve(s.size() + 2);
  out.push_back('\'');
  for (char c : s) {
    if (c == '\'') {
      out += "'\"'\"'";
    } else {
      out.push_back(c);
    }
  }
  out.push_back('\'');
  return out;
}

}  // namespace

std::string emit_makefile(const EmittedBuildManifest& manifest) {
  std::vector<std::string> cc_sources = manifest.cc_sources;
  std::vector<std::string> headers = manifest.headers;
  std::vector<std::string> pas_sources = manifest.pas_sources;
  std::vector<std::string> include_dirs = manifest.include_dirs;
  sort_unique(&cc_sources);
  sort_unique(&headers);
  sort_unique(&pas_sources);
  std::vector<std::string> include_dirs_unique;
  for (const auto& dir : include_dirs) {
    if (std::find(include_dirs_unique.begin(), include_dirs_unique.end(), dir) ==
        include_dirs_unique.end()) {
      include_dirs_unique.push_back(dir);
    }
  }
  include_dirs.swap(include_dirs_unique);

  std::ostringstream out;
  out << "# generated by tp2cc\n";
  out << "# Regeneration rules intentionally omit -m so normal Pascal source\n";
  out << "# updates do not rewrite this generated Makefile and trigger GNU make's\n";
  out << "# makefile-remake restart path.\n";
  out << "# The runtime header lives under include/tp2cc_rt both in-tree and\n";
  out << "# after install; use the concrete include roots captured when tp2cc\n";
  out << "# generated this file.\n";
  out << "CXX = g++\n";
  out << "CC = gcc\n";
  out << "TP2CC = "
      << (manifest.tp2cc_program.empty() ? "tp2cc" : manifest.tp2cc_program)
      << '\n';
  out << "CPPFLAGS = -I.";
  for (const auto& dir : include_dirs) {
    out << " -I" << dir;
  }
  out << '\n';
  out << "CXXFLAGS = -std=gnu++20 -O0 -pipe "
         "-Wno-narrowing\n";
  out << "CFLAGS = -std=gnu11 -O0 -pipe\n";
  out << "EXTRA_OBJS =\n";
  out << "LDFLAGS =\n";
  out << "LDLIBS = -lm\n\n";

  write_list(out, "CC_SRCS", cc_sources);
  write_list(out, "HDRS", headers);
  write_list(out, "PAS_SRCS", pas_sources);
  out << "CC_OBJS := $(CC_SRCS:.cc=.o)\n";
  if (!manifest.program_name.empty()) {
    out << "PROGRAM = " << manifest.program_name << '\n';
  }
  out << '\n';

  out << ".PHONY: all objects clean\n";
  if (!manifest.program_name.empty()) {
    out << "all: $(PROGRAM)\n";
  } else {
    out << "all: objects\n";
  }
  out << "objects: $(CC_OBJS)\n\n";

  if (!pas_sources.empty() && !manifest.tp2cc_args.empty()) {
    out << "$(CC_SRCS) $(HDRS): $(PAS_SRCS)\n";
    out << "\t$(TP2CC)";
    for (const auto& arg : manifest.tp2cc_args) {
      out << ' ' << shell_quote(arg);
    }
    out << "\n\n";
  }

  out << "p_%.o: p_%.cc $(HDRS)\n";
  out << "\t$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@\n\n";

  if (!manifest.program_name.empty()) {
    out << "$(PROGRAM): $(CC_OBJS) $(EXTRA_OBJS)\n";
    out << "\t$(CXX) $(CXXFLAGS) $(LDFLAGS) $^ $(LDLIBS) -o $@\n\n";
  }

  out << "clean:\n";
  out << "\trm -f $(CC_OBJS)";
  if (!manifest.program_name.empty()) out << " $(PROGRAM)";
  out << '\n';
  return out.str();
}

}  // namespace tp2cc
